[package]
name = "covidpass"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dgc = "0.0"
qrcode = "0.12"
image = "0.23.14"
libadwaita = "0.1"
gtk4 = "0.4"
curl = "0.4"