[package]
name = "covidpass"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
greenpass = { path = "../greenpass", package = "greenpass"}
greenpass_crates = { version = "0.1.0", package = "greenpass"}
qrcode = "0.12"
image = "0.23"
gtk4 = "0.4"

[features]
default = ["local"]
crates = []
local = []