name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
 
jobs:
  build:
    name: ubuntu 21.04
    runs-on: ubuntu-20.04
    container: ubuntu:21.04

    steps:
    - uses: actions/checkout@v2.4.0
    - name: Install GTK libraries
      run: sudo apt-get install libgtk-4-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose